name: Build the application

on:
  push:
    branches-ignore:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false

    - name: Install and Build 🔧
      run: |
        npm install
        npm run build
